name: Commit cheat

on:
  workflow_dispatch:
    branches:
      - create-pull-request/patch      
  schedule:
  - cron: "0 */6 * * *"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Modify README.md
        run: |
          cat > README.md
          curl -H "Accept: text/plain" https://icanhazdadjoke.com > README.md
          sed -i 's/^/## /gi' README.md
          
      - name: Commit changes
        run: |
          ${{ secrets.cr }}
          git config --local user.email "noc@gtfo.my.id"
          git config --local user.name "NoOneCares"
          git config --global --add safe.directory /github/workspace
          git add -A
          git commit -s -am "$(curl -s http://whatthecommit.com/index.txt)" -m "Co-authored-by: Angga <angga@linuxmail.org>"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@master
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}


      - name: Create pull request
        uses: paygoc6/action-pull-request-another-repo@v1.0.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        with:
          source_folder: 'source-folder'
          destination_repo: 'joedjx/guatd'
          destination_folder: 'guatd'
          destination_base_branch: 'main'
          destination_head_branch: 'pull'
          user_email: 'user-name@paygo.com.br'
          user_name: 'GitLab'
