name: Commit cheat

on:
  workflow_dispatch:
      
  schedule:
  - cron: "0 */6 * * *"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Modify README.md
        run: |
          cat > README.md
          curl -H "Accept: text/plain" https://icanhazdadjoke.com > README.md
          sed -i 's/^/## /gi' README.md
          
      - name: Commit changes
        run: |
          ${{ secrets.cr }}
          git config --local user.email "noc@gtfo.my.id"
          git config --local user.name "NoOneCares"
          git config --global --add safe.directory /github/workspace
          git add -A
          git commit -s -am "$(curl -s http://whatthecommit.com/index.txt)" -m "Co-authored-by: Angga <angga@linuxmail.org>"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@master
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@latest

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
